Repository neo4j/docs-getting-started, pull requests merged in 2021-11, with the labels that each got.

#51 Remove prerelease attribute from component descriptor
  antora.yml
Labels: 4.4

#52 Cypher syntax change
  modules/ROOT/pages/cypher-intro/load-csv.adoc
  modules/ROOT/pages/cypher-intro/schema.adoc
Labels: documentation, 4.4

#53 Change xrefs from 4.4-preview to 4.4
  modules/ROOT/pages/cypher-intro/index.adoc
  modules/ROOT/pages/cypher-intro/load-csv.adoc
  modules/ROOT/pages/cypher-intro/schema.adoc
  modules/ROOT/pages/get-started-with-neo4j.adoc
  modules/ROOT/pages/graphdb-concepts.adoc
Labels: 4.4, cherry-pick-this-to-dev

#54 Dev show indexes
  modules/ROOT/images/cypher-intro-schema-data.svg
  modules/ROOT/images/cypher-intro-schema01.svg
  modules/ROOT/pages/cypher-intro/index.adoc
  modules/ROOT/pages/cypher-intro/load-csv.adoc
  modules/ROOT/pages/cypher-intro/schema.adoc
  modules/ROOT/pages/get-started-with-neo4j.adoc
  modules/ROOT/pages/graphdb-concepts.adoc
Labels: 4.4, cherry-pick-this-to-4.4, dev

#55 Dev show indexes (#54)
  modules/ROOT/images/cypher-intro-schema-data.svg
  modules/ROOT/images/cypher-intro-schema01.svg
  modules/ROOT/pages/cypher-intro/schema.adoc
Labels: 4.4, cherry-picked

#56 Remove deprecated note in schema page
  modules/ROOT/pages/cypher-intro/schema.adoc
Labels: 5.0, breaking change
