Repository neo4j/docs-getting-started, pull requests merged in 2022-12, with the labels that each got.

#159 Fix lists syntax
  modules/ROOT/pages/data-import/csv-import.adoc
Labels: 4.4

#156 Update the chapter according to the syntax changes of v5
  modules/ROOT/pages/data-import/csv-import.adoc
Labels: 5.x

#162 Update 'Neo4j - OGM' section
  modules/ROOT/pages/languages-guides/java/neo4j-ogm.adoc
Labels: 5.x

#164 5.3 publish
  antora.yml
  publish.yml
Labels: 5.3

#161 Update the first pages with a new image and restructure them
  modules/ROOT/content-nav.adoc
  modules/ROOT/images/colored-tile-graph-arr.svg
  modules/ROOT/images/neo4j-architecture-diagram.svg
  modules/ROOT/pages/get-started-with-neo4j/graph-database.adoc
  modules/ROOT/pages/get-started-with-neo4j/graph-platform.adoc
  modules/ROOT/pages/get-started-with-neo4j/index.adoc
  modules/ROOT/pages/index.adoc
Labels: 5.x
