Repository neo4j/docs-getting-started, pull requests merged in 2022-11, with the labels that each got.

#141 moved bloom to a more prominent position
  modules/ROOT/pages/graph-visualization/graph-visualization-tools.adoc
  modules/ROOT/pages/graph-visualization/graph-visualization.adoc
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.0, 5.x

#143 moved bloom to a more prominent position
  modules/ROOT/pages/graph-visualization/graph-visualization-tools.adoc
  modules/ROOT/pages/graph-visualization/graph-visualization.adoc
Labels: cherry-picked, dev

#144 Fix the cluster terminology for v5
  modules/ROOT/pages/cypher-intro/results.adoc
  modules/ROOT/pages/get-started-with-neo4j/index.adoc
  modules/ROOT/pages/integration-tools/integration.adoc
  modules/ROOT/pages/languages-guides/index.adoc
  modules/ROOT/pages/languages-guides/java/java-intro.adoc
  modules/ROOT/pages/languages-guides/neo4j-dotnet.adoc
  modules/ROOT/pages/languages-guides/neo4j-go.adoc
  modules/ROOT/pages/languages-guides/neo4j-javascript.adoc
  modules/ROOT/pages/languages-guides/neo4j-python.adoc
Labels: 5.x

#133 Edit the chapter 'Updating the data' and replace images for Cypher query results
  modules/ROOT/images/cypher_graph_addProp-arr.svg
  modules/ROOT/images/cypher_graph_mergeFriend-arr.svg
  modules/ROOT/images/cypher_graph_mergeFriendRel-arr.svg
  modules/ROOT/images/old_images/cypher_graph_addProp.jpg
  modules/ROOT/images/old_images/cypher_graph_addRelProp.jpg
  modules/ROOT/images/old_images/cypher_graph_delNode.jpg
  modules/ROOT/images/old_images/cypher_graph_delProp.jpg
  modules/ROOT/images/old_images/cypher_graph_delRel.jpg
  modules/ROOT/images/old_images/cypher_graph_mergeFriend.jpg
  modules/ROOT/images/people-technologies-graph-arr.svg
  modules/ROOT/pages/cypher-intro/updating.adoc
Labels: 4.4, cherry-pick-this-to-5.0

#124 Update Getting the correct results and other images
  modules/ROOT/content-nav.adoc
  modules/ROOT/images/cypher-filter-exists-ptrn-arr.svg
  modules/ROOT/images/cypher-filter-exists-relProp-arr.svg
  modules/ROOT/images/cypher-filter-ranges-arr.svg
  modules/ROOT/images/cypher-intro-results01-arr.svg
  modules/ROOT/images/old_images/colored-tile-graph.png
  modules/ROOT/images/old_images/cypher-intro-patterns-in-practice01.svg
  modules/ROOT/images/old_images/cypher-intro-patterns-in-practice02.svg
  modules/ROOT/images/old_images/cypher-intro-patterns-in-practice03.svg
  modules/ROOT/images/old_images/cypher-intro-patterns-in-practice04.svg
  modules/ROOT/images/old_images/cypher-intro-patterns-in-practice05.svg
  modules/ROOT/images/old_images/cypher-intro-patterns-in-practice06.svg
  modules/ROOT/images/old_images/cypher-intro-patterns-in-practice07.svg
  modules/ROOT/images/old_images/cypher_agg_count.jpg
  modules/ROOT/images/old_images/cypher_agg_count_prop.jpg
  modules/ROOT/images/old_images/cypher_agg_count_results.jpg
  modules/ROOT/images/old_images/cypher_agg_size.jpg
  modules/ROOT/images/old_images/cypher_agg_sizePath.jpg
  modules/ROOT/images/old_images/cypher_filter_exists_nodeProp.jpg
  modules/ROOT/images/old_images/cypher_filter_exists_ptrn.jpg
  modules/ROOT/images/old_images/cypher_filter_exists_relProp.jpg
  modules/ROOT/images/old_images/cypher_filter_extPattern.jpg
  modules/ROOT/images/old_images/cypher_filter_list.jpg
  modules/ROOT/images/old_images/cypher_filter_notExists_ptrn.jpg
  modules/ROOT/images/old_images/cypher_filter_optMatch.jpg
  modules/ROOT/images/old_images/cypher_filter_ranges.jpg
  modules/ROOT/images/old_images/cypher_filter_regex.jpg
  modules/ROOT/images/old_images/cypher_filter_twoPattern.jpg
  modules/ROOT/images/old_images/cypher_graph_nodes.png
  modules/ROOT/images/old_images/cypher_graph_props.png
  modules/ROOT/images/old_images/cypher_graph_rels.png
  modules/ROOT/images/old_images/cypher_graph_v1.png
  modules/ROOT/images/old_images/cypher_learning.png
  modules/ROOT/images/old_images/cypher_results_distinct_user.jpg
  modules/ROOT/images/old_images/cypher_results_limit.jpg
  modules/ROOT/images/old_images/cypher_results_order_experience.jpg
  modules/ROOT/images/old_images/cypher_results_order_names.jpg
  modules/ROOT/images/old_images/cypher_results_unwind_numList.jpg
  modules/ROOT/images/old_images/cypher_results_unwind_strList.jpg
  modules/ROOT/images/old_images/graph-example.png
  modules/ROOT/images/old_images/sample-cypher.png
  modules/ROOT/images/people-technologies-graph-arr.svg
  modules/ROOT/pages/cypher-intro/results.adoc
Labels: 4.4, cherry-pick-this-to-5.0

#147 Cherry-pick #133
  modules/ROOT/images/cypher_graph_addProp-arr.svg
  modules/ROOT/images/cypher_graph_mergeFriend-arr.svg
  modules/ROOT/images/cypher_graph_mergeFriendRel-arr.svg
  modules/ROOT/images/old_images/cypher_graph_addProp.jpg
  modules/ROOT/images/old_images/cypher_graph_addRelProp.jpg
  modules/ROOT/images/old_images/cypher_graph_delNode.jpg
  modules/ROOT/images/old_images/cypher_graph_delProp.jpg
  modules/ROOT/images/old_images/cypher_graph_delRel.jpg
  modules/ROOT/images/old_images/cypher_graph_mergeFriend.jpg
  modules/ROOT/images/people-technologies-graph-arr.svg
  modules/ROOT/pages/cypher-intro/updating.adoc
Labels: cherry-picked, 5.x

#150 Remove the CTA for NODES (#149)
  publish.yml
Labels: cherry-picked

#151 Update antora attributes
  antora.yml
Labels: 5.2

#152 Update the chapter 'Composing large statements' v4.4
  modules/ROOT/images/old_images/cypher_results_with.jpg
  modules/ROOT/images/old_images/cypher_results_with_filter.jpg
  modules/ROOT/images/people-technologies-graph-arr.svg
  modules/ROOT/pages/cypher-intro/large-statements.adoc
Labels: 4.4
