Repository neo4j/docs-getting-started, pull requests merged in 2023-03, with the labels that each got.

#217 Rename drivers section
  modules/ROOT/pages/languages-guides/index.adoc
Labels: dev, cherry-pick-this-to-5.x

#218 Restructure the section on Neo4j Community Drivers
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/languages-guides/community-drivers/index.adoc
  modules/ROOT/pages/languages-guides/community-drivers/java-third-party.adoc
  modules/ROOT/pages/languages-guides/community-drivers/neo4j-erlang-elixir.adoc
  modules/ROOT/pages/languages-guides/community-drivers/neo4j-perl.adoc
  modules/ROOT/pages/languages-guides/community-drivers/neo4j-php.adoc
  modules/ROOT/pages/languages-guides/community-drivers/neo4j-ruby.adoc
  modules/ROOT/pages/languages-guides/integration-tools/integration.adoc
  modules/ROOT/pages/languages-guides/neo4j-dotnet.adoc
  modules/ROOT/pages/languages-guides/neo4j-go.adoc
  modules/ROOT/pages/languages-guides/neo4j-javascript.adoc
  modules/ROOT/pages/languages-guides/neo4j-python.adoc
Labels: cherry-pick-this-to-5.x

#219 Restructure the section on Neo4j Community Drivers (#218)
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/languages-guides/community-drivers/index.adoc
  modules/ROOT/pages/languages-guides/community-drivers/java-third-party.adoc
  modules/ROOT/pages/languages-guides/community-drivers/neo4j-erlang-elixir.adoc
  modules/ROOT/pages/languages-guides/community-drivers/neo4j-perl.adoc
  modules/ROOT/pages/languages-guides/community-drivers/neo4j-php.adoc
  modules/ROOT/pages/languages-guides/community-drivers/neo4j-ruby.adoc
  modules/ROOT/pages/languages-guides/integration-tools/integration.adoc
  modules/ROOT/pages/languages-guides/neo4j-dotnet.adoc
  modules/ROOT/pages/languages-guides/neo4j-go.adoc
  modules/ROOT/pages/languages-guides/neo4j-javascript.adoc
  modules/ROOT/pages/languages-guides/neo4j-python.adoc
Labels: cherry-picked

#220 Rename drivers section (#217)
  modules/ROOT/pages/languages-guides/index.adoc
Labels: cherry-picked

#221 Update Neo4j version on the first page
  antora.yml
  modules/ROOT/pages/index.adoc
Labels: 5.x

#228 Update Neo4j version
  antora.yml
Labels: 5.7

#230 Fixes for PDF
  modules/ROOT/pages/appendix/graphdb-concepts/graphdb-vs-nosql.adoc
  modules/ROOT/pages/appendix/graphdb-concepts/graphdb-vs-rdbms.adoc
  modules/ROOT/pages/cypher-intro/index.adoc
  modules/ROOT/pages/get-started-with-neo4j/graph-database.adoc
  modules/ROOT/pages/index.adoc
Labels: dev, cherry-pick-this-to-5.x

#231 Update images in the Graph model refactoring and Example datasets sec…
  modules/ROOT/images/airline-arr.svg
  modules/ROOT/images/boolean_refactoring-arr.svg
  modules/ROOT/images/flight_node-arr.svg
  modules/ROOT/images/initial_model-arr.svg
  modules/ROOT/images/old_images/airline.png
  modules/ROOT/images/old_images/boolean_refactoring.png
  modules/ROOT/images/old_images/flight_node.png
  modules/ROOT/images/old_images/initial_model.png
  modules/ROOT/images/stackoverflow_graph_model-arr.svg
  modules/ROOT/pages/appendix/example-data.adoc
  modules/ROOT/pages/data-modeling/graph-model-refactoring.adoc
Labels: dev, cherry-pick-this-to-5.x
