Repository neo4j/docs-getting-started, pull requests merged in 2023-06, with the labels that each got.

#269 Fix the broken links to the Cypher manual
  modules/ROOT/pages/cypher-intro/schema.adoc
Labels: dev, cherry-pick-this-to-main

#270 Fix the broken links to the Cypher manual (#269)
  modules/ROOT/pages/cypher-intro/schema.adoc
Labels: cherry-picked, main

#271 Add the trademark icon on the 1st usage of Cypher (#268)
  modules/ROOT/pages/appendix/tutorials/guide-cypher-basics.adoc
  modules/ROOT/pages/cypher-intro/index.adoc
  modules/ROOT/pages/data-modeling/graph-model-refactoring.adoc
  modules/ROOT/pages/get-started-with-neo4j/graph-database.adoc
  modules/ROOT/pages/get-started-with-neo4j/index.adoc
  modules/ROOT/pages/graph-visualization/graph-visualization.adoc
  modules/ROOT/pages/index.adoc
  package.json
  preview.yml
  publish.yml
Labels: cherry-picked, main

#275 Broken links to Cypher new section on values and types
  modules/ROOT/pages/cypher-intro/dates-datetimes-durations.adoc
  modules/ROOT/pages/cypher-intro/index.adoc
Labels: dev, cherry-pick-this-to-main

#273 Fix the broken link and add CREATE query on the page Updating the data
  modules/ROOT/pages/cypher-intro/updating.adoc
Labels: dev, cherry-pick-this-to-main

#278 Add CREATE query and update images (#274)
  modules/ROOT/images/cypher-filter-exists-relProp-arr.svg
  modules/ROOT/images/people-companies-technologies-rel-property.svg
  modules/ROOT/pages/cypher-intro/results.adoc
Labels: cherry-picked, dev

#279 Added Quarkus guide page (#172)
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/appendix/tutorials/guide-import-desktop-csv.adoc
  modules/ROOT/pages/get-started-with-neo4j/graph-database.adoc
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/languages-guides/index.adoc
  modules/ROOT/pages/languages-guides/java/java-frameworks.adoc
  modules/ROOT/pages/languages-guides/java/quarkus.adoc
Labels: cherry-picked, dev

#276 Broken links to Cypher new section on values and types (#275)
  modules/ROOT/pages/cypher-intro/dates-datetimes-durations.adoc
  modules/ROOT/pages/cypher-intro/index.adoc
Labels: cherry-picked, main

#265 Restructure the section on the community drivers
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/languages-guides/community-drivers/index.adoc
Labels: dev, cherry-pick-this-to-main, WIP

#282 Add CREATE query to reproduce the dataset
  modules/ROOT/pages/cypher-intro/large-statements.adoc
Labels: dev, cherry-pick-this-to-main

#283 Add CREATE query to reproduce the dataset (#282)
  modules/ROOT/pages/cypher-intro/large-statements.adoc
Labels: cherry-picked, main
