Repository neo4j/docs-getting-started, pull requests merged in 2023-01, with the labels that each got.

#165 Http-API fix for updated syntax + docs link
  modules/ROOT/pages/languages-guides/index.adoc
Labels: 4.4

#166 Update tutorials on how to import CSV files
  modules/ROOT/images/developer-desktop-csv-import-data_model-arr.svg
  modules/ROOT/images/getting-started-load-csv01-arr.svg
  modules/ROOT/images/getting-started-load-csv02-arr.svg
  modules/ROOT/images/old_images/developer-desktop-csv-import-data_model.png
  modules/ROOT/images/old_images/getting-started-load-csv01.svg
  modules/ROOT/images/old_images/getting-started-load-csv02.svg
  modules/ROOT/pages/appendix/tutorials/guide-import-desktop-csv.adoc
  modules/ROOT/pages/cypher-intro/load-csv.adoc
Labels: 5.x

#168 Replace images with the new ones
  modules/ROOT/images/ImplementedModel.png
  modules/ROOT/images/matrix_whiteboard_model2.svg
  modules/ROOT/images/matrix_whiteboard_model3-arr.svg
  modules/ROOT/images/matrix_whiteboard_model4.svg
  modules/ROOT/images/modeling_johnsally_labels-arr.svg
  modules/ROOT/images/modeling_johnsally_nodes-arr.svg
  modules/ROOT/images/modeling_johnsally_properties-arr.svg
  modules/ROOT/images/modeling_johnsally_relationships-arr.svg
  modules/ROOT/images/old_images/matrix_whiteboard_model2.png
  modules/ROOT/images/old_images/matrix_whiteboard_model3.png
  modules/ROOT/images/old_images/matrix_whiteboard_model4.png
  modules/ROOT/images/old_images/modeling_johnsally_labels.jpg
  modules/ROOT/images/old_images/modeling_johnsally_nodes.jpg
  modules/ROOT/images/old_images/modeling_johnsally_properties.jpg
  modules/ROOT/images/old_images/modeling_johnsally_relationships.jpg
  modules/ROOT/images/property_graph_elements-arr.svg
  modules/ROOT/pages/data-modeling/guide-data-modeling.adoc
Labels: 5.x

#174 Update bolt library specs by latest major update (#173)
  modules/ROOT/pages/languages-guides/neo4j-php.adoc
Labels: cherry-picked, 5.x

#176 Update tutorials on how to import CSV files (#166)
  modules/ROOT/images/developer-desktop-csv-import-data_model-arr.svg
  modules/ROOT/images/getting-started-load-csv01-arr.svg
  modules/ROOT/images/getting-started-load-csv02-arr.svg
  modules/ROOT/images/old_images/developer-desktop-csv-import-data_model.png
  modules/ROOT/images/old_images/getting-started-load-csv01.svg
  modules/ROOT/images/old_images/getting-started-load-csv02.svg
  modules/ROOT/pages/appendix/tutorials/guide-import-desktop-csv.adoc
  modules/ROOT/pages/cypher-intro/load-csv.adoc
Labels: cherry-picked, dev

#178 Replace images with the new ones (#168)
  modules/ROOT/images/ImplementedModel.png
  modules/ROOT/images/matrix_whiteboard_model2.svg
  modules/ROOT/images/matrix_whiteboard_model3-arr.svg
  modules/ROOT/images/matrix_whiteboard_model4.svg
  modules/ROOT/images/modeling_johnsally_labels-arr.svg
  modules/ROOT/images/modeling_johnsally_nodes-arr.svg
  modules/ROOT/images/modeling_johnsally_properties-arr.svg
  modules/ROOT/images/modeling_johnsally_relationships-arr.svg
  modules/ROOT/images/old_images/matrix_whiteboard_model2.png
  modules/ROOT/images/old_images/matrix_whiteboard_model3.png
  modules/ROOT/images/old_images/matrix_whiteboard_model4.png
  modules/ROOT/images/old_images/modeling_johnsally_labels.jpg
  modules/ROOT/images/old_images/modeling_johnsally_nodes.jpg
  modules/ROOT/images/old_images/modeling_johnsally_properties.jpg
  modules/ROOT/images/old_images/modeling_johnsally_relationships.jpg
  modules/ROOT/images/property_graph_elements-arr.svg
  modules/ROOT/pages/data-modeling/guide-data-modeling.adoc
Labels: cherry-picked, dev

#169 Update the attributes' list in the antora.yml file
  antora.yml
  modules/ROOT/pages/languages-guides/java/java-intro.adoc
  modules/ROOT/pages/languages-guides/java/neo4j-ogm.adoc
  modules/ROOT/pages/languages-guides/java/spring-data-neo4j.adoc
  modules/ROOT/pages/languages-guides/neo4j-dotnet.adoc
  modules/ROOT/pages/languages-guides/neo4j-go.adoc
  modules/ROOT/pages/languages-guides/neo4j-javascript.adoc
  modules/ROOT/pages/languages-guides/neo4j-python.adoc
Labels: dev

#170 Update attributes in antora file
  antora.yml
  modules/ROOT/pages/languages-guides/java/java-intro.adoc
  modules/ROOT/pages/languages-guides/java/neo4j-ogm.adoc
  modules/ROOT/pages/languages-guides/java/spring-data-neo4j.adoc
  modules/ROOT/pages/languages-guides/neo4j-dotnet.adoc
  modules/ROOT/pages/languages-guides/neo4j-go.adoc
  modules/ROOT/pages/languages-guides/neo4j-javascript.adoc
  modules/ROOT/pages/languages-guides/neo4j-python.adoc
Labels: 5.x

#181 Add GraphAcademy button to the Cypher section
  modules/ROOT/pages/cypher-intro/index.adoc
  modules/ROOT/pages/cypher-intro/large-statements.adoc
  modules/ROOT/pages/cypher-intro/load-csv.adoc
  modules/ROOT/pages/cypher-intro/patterns-in-practice.adoc
  modules/ROOT/pages/cypher-intro/patterns.adoc
  modules/ROOT/pages/cypher-intro/procedures-functions.adoc
  modules/ROOT/pages/cypher-intro/resources.adoc
  modules/ROOT/pages/cypher-intro/results.adoc
  modules/ROOT/pages/cypher-intro/schema.adoc
Labels: dev, cherry-pick-this-to-5.x

#183 Add GraphAcademy button to the Cypher section (#181)
  modules/ROOT/pages/cypher-intro/index.adoc
  modules/ROOT/pages/cypher-intro/large-statements.adoc
  modules/ROOT/pages/cypher-intro/load-csv.adoc
  modules/ROOT/pages/cypher-intro/patterns-in-practice.adoc
  modules/ROOT/pages/cypher-intro/patterns.adoc
  modules/ROOT/pages/cypher-intro/procedures-functions.adoc
  modules/ROOT/pages/cypher-intro/resources.adoc
  modules/ROOT/pages/cypher-intro/results.adoc
  modules/ROOT/pages/cypher-intro/schema.adoc
Labels: cherry-picked, 5.x

#184 Update Neo4j version
  antora.yml
Labels: 5.5

#185 Link to Cypher Cheat Sheet v4.4
  modules/ROOT/pages/appendix/getting-started-resources.adoc
Labels: 4.4

#186 Update information on Java version compatible with 5.x drivers series
  modules/ROOT/pages/languages-guides/java/java-intro.adoc
Labels: dev, cherry-pick-this-to-5.x

#187 Update information on Java version compatible with 5.x drivers series…
  modules/ROOT/pages/languages-guides/java/java-intro.adoc
Labels: cherry-picked, 5.x

#188 Add links to the GraphAcademy courses
  modules/ROOT/pages/data-import/index.adoc
  modules/ROOT/pages/data-modeling/index.adoc
  modules/ROOT/pages/get-started-with-neo4j/graph-database.adoc
  modules/ROOT/pages/get-started-with-neo4j/index.adoc
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/languages-guides/index.adoc
Labels: dev, cherry-pick-this-to-5.x

#190 Update driver version numbers
  antora.yml
Labels: dev, cherry-pick-this-to-5.x

#191 Update driver version numbers (#190)
  antora.yml
Labels: cherry-picked, 5.x
