Repository neo4j/docs-getting-started, pull requests merged in 2023-04, with the labels that each got.

#233 Update driver version numbers to 5.7
  antora.yml
Labels: 5.x

#224 Update links to the APOC docs
  modules/ROOT/pages/appendix/example-data.adoc
  modules/ROOT/pages/appendix/tutorials/guide-import-relational-and-etl.adoc
  modules/ROOT/pages/cypher-intro/dates-datetimes-durations.adoc
  modules/ROOT/pages/cypher-intro/procedures-functions.adoc
  modules/ROOT/pages/data-import/json-rest-api-import.adoc
  modules/ROOT/pages/data-import/relational-to-graph-import.adoc
  modules/ROOT/pages/data-modeling/graph-model-refactoring.adoc
  modules/ROOT/pages/data-modeling/modeling-tips.adoc
  modules/ROOT/pages/languages-guides/java/java-procedures.adoc
Labels: dev, cherry-pick-this-to-5.x

#234 Update links to the APOC docs (#224)
  modules/ROOT/pages/appendix/example-data.adoc
  modules/ROOT/pages/appendix/tutorials/guide-import-relational-and-etl.adoc
  modules/ROOT/pages/cypher-intro/dates-datetimes-durations.adoc
  modules/ROOT/pages/cypher-intro/procedures-functions.adoc
  modules/ROOT/pages/data-import/json-rest-api-import.adoc
  modules/ROOT/pages/data-import/relational-to-graph-import.adoc
  modules/ROOT/pages/data-modeling/graph-model-refactoring.adoc
  modules/ROOT/pages/data-modeling/modeling-tips.adoc
  modules/ROOT/pages/languages-guides/java/java-procedures.adoc
Labels: cherry-picked, 5.x

#235 fixing link to neotypes docs, now instead leading to main page
  modules/ROOT/pages/languages-guides/community-drivers/java-third-party.adoc
Labels: bug, cherry-pick-this-to-dev, 5.x

#238 fixing link to neotypes docs, now instead leading to main page (#235)
  modules/ROOT/pages/languages-guides/community-drivers/java-third-party.adoc
Labels: cherry-picked, dev

#239 Changing links from http to https for better indexation (#236)
  modules/ROOT/pages/appendix/tutorials/guide-build-a-recommendation-engine.adoc
  modules/ROOT/pages/data-modeling/guide-data-modeling.adoc
  modules/ROOT/pages/languages-guides/community-drivers/neo4j-ruby.adoc
Labels: cherry-picked, dev

#240 Changing links from http to https for better indexation (#236)
  modules/ROOT/pages/appendix/tutorials/guide-build-a-recommendation-engine.adoc
  modules/ROOT/pages/data-modeling/guide-data-modeling.adoc
  modules/ROOT/pages/languages-guides/neo4j-ruby.adoc
Labels: 4.4, cherry-picked

#241 Fix the broken link to the Spring-Neo4j changelog (#237)
  modules/ROOT/pages/languages-guides/java/spring-data-neo4j.adoc
Labels: cherry-picked, 5.x

#244 Update images on the page Graph db concepts
  modules/ROOT/images/graph_concept_three_nodes-arr.svg
  modules/ROOT/images/graph_example_relationship-arr.svg
  modules/ROOT/images/graph_simple-arr.svg
  modules/ROOT/images/graph_single_node-arr.svg
  modules/ROOT/images/graphdb-nodes-and-rel-arr.svg
  modules/ROOT/images/graphdb-nodes-and-rel-self-arr.svg
  modules/ROOT/images/graphdb-path-arr.svg
  modules/ROOT/images/graphdb-path-example-loop-arr.svg
  modules/ROOT/images/graphdb-path-zero-arr.svg
  modules/ROOT/images/graphdb-simple-labels-multi-arr.svg
  modules/ROOT/images/graphdb-traversal-arr.svg
  modules/ROOT/images/old_images/graph_concept_three_nodes.svg
  modules/ROOT/images/old_images/graph_example_relationship.svg
  modules/ROOT/images/old_images/graph_simple.svg
  modules/ROOT/images/old_images/graph_single_node.svg
  modules/ROOT/images/old_images/graphdb-nodes-and-rel-self.svg
  modules/ROOT/images/old_images/graphdb-nodes-and-rel.svg
  modules/ROOT/images/old_images/graphdb-path-example-loop.svg
  modules/ROOT/images/old_images/graphdb-path-zero.svg
  modules/ROOT/images/old_images/graphdb-path.svg
  modules/ROOT/images/old_images/graphdb-simple-labels-multi.svg
  modules/ROOT/images/old_images/graphdb-traversal.svg
  modules/ROOT/pages/appendix/graphdb-concepts/index.adoc
Labels: dev, cherry-pick-this-to-5.x

#245 Update images on the page Graph db concepts (#244)
  modules/ROOT/images/graph_concept_three_nodes-arr.svg
  modules/ROOT/images/graph_example_relationship-arr.svg
  modules/ROOT/images/graph_simple-arr.svg
  modules/ROOT/images/graph_single_node-arr.svg
  modules/ROOT/images/graphdb-nodes-and-rel-arr.svg
  modules/ROOT/images/graphdb-nodes-and-rel-self-arr.svg
  modules/ROOT/images/graphdb-path-arr.svg
  modules/ROOT/images/graphdb-path-example-loop-arr.svg
  modules/ROOT/images/graphdb-path-zero-arr.svg
  modules/ROOT/images/graphdb-simple-labels-multi-arr.svg
  modules/ROOT/images/graphdb-traversal-arr.svg
  modules/ROOT/images/old_images/graph_concept_three_nodes.svg
  modules/ROOT/images/old_images/graph_example_relationship.svg
  modules/ROOT/images/old_images/graph_simple.svg
  modules/ROOT/images/old_images/graph_single_node.svg
  modules/ROOT/images/old_images/graphdb-nodes-and-rel-self.svg
  modules/ROOT/images/old_images/graphdb-nodes-and-rel.svg
  modules/ROOT/images/old_images/graphdb-path-example-loop.svg
  modules/ROOT/images/old_images/graphdb-path-zero.svg
  modules/ROOT/images/old_images/graphdb-path.svg
  modules/ROOT/images/old_images/graphdb-simple-labels-multi.svg
  modules/ROOT/images/old_images/graphdb-traversal.svg
  modules/ROOT/pages/appendix/graphdb-concepts/index.adoc
Labels: cherry-picked, 5.x

#243 Update content on how to extend Cypher
  modules/ROOT/pages/cypher-intro/procedures-functions.adoc
Labels: dev, cherry-pick-this-to-5.x

#247 Update content on how to extend Cypher (#243)
  modules/ROOT/pages/cypher-intro/procedures-functions.adoc
Labels: cherry-picked, 5.x

#248 Update Neo4j version
  antora.yml
Labels: 5.8

#249 Remove versions
  antora.yml
  publish.yml
Labels: main
