Repository neo4j/docs-getting-started, pull requests merged in 2023-08, with the labels that each got.

#301 Update ui-bundle url
  preview.yml
  publish.yml
Labels: dev, cherry-pick-this-to-main

#302 update packages - npm audit
  package.json
Labels: dev, cherry-pick-this-to-main

#303 Fix error in the Cypher Shell command
  modules/ROOT/pages/cypher-intro/load-csv.adoc
Labels: dev, cherry-pick-this-to-main

#304 Fix error in the Cypher Shell command (#303)
  modules/ROOT/pages/cypher-intro/load-csv.adoc
Labels: cherry-picked, main

#305 Explain the query result
  modules/ROOT/pages/cypher-intro/results.adoc
Labels: dev, cherry-pick-this-to-main

#307 Explain the query result (#305)
  modules/ROOT/pages/cypher-intro/results.adoc
Labels: cherry-picked, main

#308 Add information about plugins
  modules/ROOT/pages/get-started-with-neo4j/index.adoc
Labels: dev, cherry-pick-this-to-main

#311 Add information about plugins (#308)
  modules/ROOT/pages/get-started-with-neo4j/index.adoc
Labels: cherry-picked, main

#300 Add introduction to Neo4j Workspace
  modules/ROOT/images/data-importer-1.png
  modules/ROOT/images/workspace_import_tab.png
  modules/ROOT/pages/data-modeling/data-modeling-tools.adoc
  modules/ROOT/pages/get-started-with-neo4j/index.adoc
  modules/ROOT/pages/index.adoc
Labels: dev, cherry-pick-this-to-main

#316 Add introduction to Neo4j Workspace (#300)
  modules/ROOT/images/data-importer-1.png
  modules/ROOT/images/workspace_import_tab.png
  modules/ROOT/pages/data-modeling/data-modeling-tools.adoc
  modules/ROOT/pages/get-started-with-neo4j/index.adoc
  modules/ROOT/pages/index.adoc
Labels: cherry-picked

#317 Fix broken links to the Cypher manual
  modules/ROOT/pages/appendix/graphdb-concepts/index.adoc
Labels: dev, cherry-pick-this-to-main

#314 Update modeling-designs.adoc
  modules/ROOT/pages/data-modeling/modeling-designs.adoc
Labels: cherry-pick-this-to-dev, main

#297 Fix or/and typo in query with 'WITH'
  modules/ROOT/pages/cypher-intro/results.adoc
Labels: cherry-pick-this-to-dev, main

#319 Add a new page on comparing Cypher and SQL (#298)
  modules/ROOT/content-nav.adoc
  modules/ROOT/images/northwind_dataset_load.png
  modules/ROOT/images/northwind_graph_workspace-arr.png
  modules/ROOT/images/northwind_graph_workspace-arr.svg
  modules/ROOT/images/northwind_schema_workspace.png
  modules/ROOT/pages/appendix/getting-started-resources.adoc
  modules/ROOT/pages/appendix/graphdb-concepts/graphdb-vs-nosql.adoc
  modules/ROOT/pages/appendix/tutorials/guide-import-relational-and-etl.adoc
  modules/ROOT/pages/cypher-intro/cypher-sql.adoc
  modules/ROOT/pages/data-modeling/data-modeling-tools.adoc
Labels: cherry-picked, main

#321 Update modeling-designs.adoc (#314)
  modules/ROOT/pages/data-modeling/modeling-designs.adoc
Labels: cherry-picked, dev

#322 Update links to the new guide on Data Importer
  modules/ROOT/pages/data-modeling/data-modeling-tools.adoc
  modules/ROOT/pages/get-started-with-neo4j/index.adoc
  modules/ROOT/pages/index.adoc
Labels: dev, cherry-pick-this-to-main

#323 Update links to the new guide on Data Importer (#322)
  modules/ROOT/pages/data-modeling/data-modeling-tools.adoc
  modules/ROOT/pages/get-started-with-neo4j/index.adoc
  modules/ROOT/pages/index.adoc
Labels: cherry-picked, main

#324 Remove mentions about Graph Data Platform
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/get-started-with-neo4j/index.adoc
  modules/ROOT/pages/index.adoc
Labels: dev, cherry-pick-this-to-main

#325 Remove mentions about Graph Data Platform (#324)
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/get-started-with-neo4j/index.adoc
  modules/ROOT/pages/index.adoc
Labels: cherry-picked, main
