Repository neo4j/docs-getting-started, pull requests merged in 2024-11, with the labels that each got.

#428 Revamp of the data modeling tools page with KB resources added to it
  modules/ROOT/images/cypher-workbench.png
  modules/ROOT/pages/data-modeling/data-modeling-tools.adoc
Labels: cherry-pick-this-to-main

#433 Revamp of the data modeling tools page with KB resources added to it #428
  modules/ROOT/images/cypher-workbench.png
  modules/ROOT/pages/data-modeling/data-modeling-tools.adoc
Labels: cherry-picked

#431 Fix the OGM page
  modules/ROOT/pages/languages-guides/java/neo4j-ogm.adoc
Labels: cherry-pick-this-to-dev, main

#436 Fix the OGM page (#431)
  modules/ROOT/pages/languages-guides/java/neo4j-ogm.adoc
Labels: cherry-picked
